package com.project.bean;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Component
public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.id
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.name
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.price
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.author
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.sales
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.stock
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.img_path
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    private String imgPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.id
     *
     * @return the value of t_book.id
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.id
     *
     * @param id the value for t_book.id
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.name
     *
     * @return the value of t_book.name
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.name
     *
     * @param name the value for t_book.name
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.price
     *
     * @return the value of t_book.price
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.price
     *
     * @param price the value for t_book.price
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.author
     *
     * @return the value of t_book.author
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.author
     *
     * @param author the value for t_book.author
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.sales
     *
     * @return the value of t_book.sales
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.sales
     *
     * @param sales the value for t_book.sales
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.stock
     *
     * @return the value of t_book.stock
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.stock
     *
     * @param stock the value for t_book.stock
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.img_path
     *
     * @return the value of t_book.img_path
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.img_path
     *
     * @param imgPath the value for t_book.img_path
     *
     * @mbg.generated Mon Feb 28 15:00:05 CST 2022
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }
}